# Generated by Django 2.1.3 on 2018-12-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(default='男', max_length=2)),
                ('age', models.IntegerField(max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
