# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-25 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(help_text='用户角色标识', max_length=64, unique=True, verbose_name='role code')),
                ('role_name', models.CharField(help_text='用户角色名', max_length=64, verbose_name='role name')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(help_text='用户角色标识', max_length=64, verbose_name='role code')),
                ('pm_code', models.CharField(help_text='权限的code', max_length=64, verbose_name='permission code')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='用户id', unique=True, verbose_name='user id')),
                ('role_codes', models.CharField(blank=True, default=None, help_text='用户角色的codes', max_length=256, verbose_name='role codes')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=set([('role_code', 'pm_code')]),
        ),
    ]
