# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20181225_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('url', models.CharField(max_length=64, verbose_name='含规则url')),
                ('is_menu', models.BooleanField(verbose_name='是否是菜单')),
            ],
            options={
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.CharField(max_length=32, verbose_name='邮件')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色表'},
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_code',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_name',
        ),
        migrations.AddField(
            model_name='role',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, to='demo.Role', verbose_name='现有的所有角色'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='demo.Permissions', verbose_name='具有的所有权限'),
        ),
    ]
