# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20190103_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
